// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAusp8621M-mMTz2wRU6ARZ9kpoYc2ITpU',
    appId: '1:566426897946:web:774e2031a9b037e4614ba3',
    messagingSenderId: '566426897946',
    projectId: 'expense-manager-396916',
    authDomain: 'expense-manager-396916.firebaseapp.com',
    storageBucket: 'expense-manager-396916.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyqayl4GAhOT8Orr1Pa3CNiVf9OtxWrA',
    appId: '1:566426897946:android:cbbb8fc2a39bd1d9614ba3',
    messagingSenderId: '566426897946',
    projectId: 'expense-manager-396916',
    storageBucket: 'expense-manager-396916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxiP9ivZrvPISiXITTX1ltIMdIgEiQe9k',
    appId: '1:566426897946:ios:23b8206cd3fd825c614ba3',
    messagingSenderId: '566426897946',
    projectId: 'expense-manager-396916',
    storageBucket: 'expense-manager-396916.appspot.com',
    androidClientId: '566426897946-gv7fmirr1omoffqtb51bns2vh3h3kv05.apps.googleusercontent.com',
    iosClientId: '566426897946-keufqu4fphgfefi2i07eb68k8v0ih7ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxiP9ivZrvPISiXITTX1ltIMdIgEiQe9k',
    appId: '1:566426897946:ios:23b8206cd3fd825c614ba3',
    messagingSenderId: '566426897946',
    projectId: 'expense-manager-396916',
    storageBucket: 'expense-manager-396916.appspot.com',
    androidClientId: '566426897946-gv7fmirr1omoffqtb51bns2vh3h3kv05.apps.googleusercontent.com',
    iosClientId: '566426897946-keufqu4fphgfefi2i07eb68k8v0ih7ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.expense',
  );
}
